# Netlify configuration for staging/production deployment

[build]
  publish = "dist"
  command = "npm run build:production"

# Production site (main branch)
[context.production]
  command = "npm run build:production"
  
[context.production.environment]
  VITE_ADMIN_ENABLED = "false"

# Staging site (dev branch)
[context.dev]
  command = "npm run build:staging"
  
[context.dev.environment]
  VITE_ADMIN_ENABLED = "true"

# Branch deploys for dev branch
[context.branch-deploy]
  command = "npm run build:staging"

[context.branch-deploy.environment]
  VITE_ADMIN_ENABLED = "true"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Redirect staging admin to proper path
[[redirects]]
  from = "/staging/admin-login"
  to = "/staging/admin-login"
  status = 200
  force = false

[[redirects]]
  from = "/staging/admin/*"
  to = "/staging/admin/:splat"
  status = 200
  force = false